name: Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Install
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: /carousel
      - name: Deploy
        if: success()
        run: |
          git config --global user.email "dev+github-chappie@qoqa.com"
          git config --global user.name "${{ github.actor }}"
          npm run deploy -x -r https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
