name: Publish Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@pierre-do'
      - run: yarn
      - run: yarn build:package
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.githubToken}}

