name: Publish Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@pierre-do'
      - name: Update package version
        run: |
          git config --global user.email "pierredominique.putallaz@gmail.com"
          git config --global user.name "${{ github.actor }}"
          npm version ${{ steps.vars.outputs.tag }}
          git commit -n -m "Bump version to ${{ steps.vars.outputs.tag }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.githubToken }}
      - name: Build
        run: |
          yarn --prod
          yarn build:package
      - name: Publish
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.githubToken }}

