name: Validate Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Install
        run: |
          npm ci
      - name: Build
        run: |
          npm run lint
        env:
          CI: true
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Install
        run: |
          npm ci
      - name: Tests
        run: |
          npm run test
        env:
          CI: true
  validate-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Install
        run: |
          npm ci
      - name: Tests
        run: |
          npm run validate:package
        env:
          CI: true
